### ISSUE TITLE
how to query for blank node subject triples

### ISSUE THREAD

**Issue by richRemer** [awwright/node-rdf#20]
Say I've got a graph that refers to a blank node object "b1".  How do I query for triples where "b1" is the subject?

```
<#me>
  a foaf:Person;
  cert:key [                             # the object here is blank node "b1"
    a cert:RSAPublicKey;       # these are the triples I want to find
    cert:exponent 65537;
    cert:modulus "..."
  ].
```

The closest I can seem to get is `graph.match("_:b1", null, null)`, which at least recognizes that I'm looking for a blank node, but throws with "unexpected BlankNode syntax".  I can also find triples related to the predicate with `graph.match(null, "cert:exponent", null)`, but that still requires that I manually filter for the subject I'm looking for.

**Comment by awwright** [comment]
@richRemer Could you please post a code sample with expected and actual output?

Speaking generally, querying for a particular blank node can be difficult because the label is just a label, there can be multiple distinct blank nodes that share the same label. You may need to get a reference to the actual BlankNode object itself, and use that.

**Comment by richRemer** [comment]
Getting a reference worked.  Thanks!  So, now I'm doing something like:

```js
let [node] = graph.match(subject, "cert:key", null).toArray();
let nestedTriples = graph.match(node, "cert:exponent", null).toArray();
```

**Comment by awwright** [comment]
@richRemer You may also like to check out the ResultSet API, you might be able to do something like:

```javascript
var nestedTriples = graph.reference(subject).rel("cert:key").rel("cert:exponent").toArray();
```
